version: "3.8"

services:
  relay:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: sh -c 'bundle exec exe/relay'
    env_file:
      - ./.env
    restart: always
    ports:
      - 2600:2600/udp
    network_mode: "host"
