#!/usr/bin/env ruby
# frozen_string_literal: true

require "udp_relay"

env_var_listen_port = "RELAY_LISTEN_PORT"
env_var_destination_address = "RELAY_DESTINATION_ADDRESS"
env_var_destination_port = "RELAY_DESTINATION_PORT"
env_var_source_id = "RELAY_SOURCE_ID"
env_var_connection_type = "RELAY_CONNECTION_TYPE"

listen_port = ENV[env_var_listen_port]
destination_address = ENV[env_var_destination_address]
destination_port = ENV[env_var_destination_port]
source_id = ENV[env_var_source_id]
connection_type = ENV[env_var_connection_type] || "UDP"

unless listen_port
  warn "No listen port configured. Set #{env_var_listen_port} environment variable"

  return
end

unless destination_address
  warn "No destination address configured. Set #{env_var_destination_address} environment variable"

  return
end

unless destination_port
  warn "No destination port configured. Set #{env_var_destination_port} environment variable"

  return
end

if connection_type.to_sym == :UDP
  UdpRelay.application.run listen_port, destination_address, destination_port, source_id
else
  UdpRelay.application_tcp.run listen_port, destination_address, destination_port, source_id
end
